### ISSUE TITLE
Rename to "rust-dist" to better align with Paketo naming convention

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-community/rust-dist#1]
The naming convention in Paketo is to not use the `-cnb` suffix. We should change the name of this repository to align with that naming convention.

**Comment by dmikusa-pivotal** [comment]
Totally agree. Do you see any complications of doing this? I believe Github will properly redirect things for us, so there shouldn't be any broken links. Any other concerns?

**Comment by ForestEckhardt** [comment]
Nothing off the top of my head. So if you want to go just change it that is fine by me.

**Comment by dmikusa-pivotal** [comment]
Sounds good, I can take this one (as well as the similar task for the other repos).

**Comment by ForestEckhardt** [comment]
Thanks!

**Comment by dmikusa-pivotal** [comment]
Done.
