### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-community/rust-dist#4]
We should add integration tests that verify that `rust` is reliably installed onto the system.

**Comment by dmikusa-pivotal** [comment]
I'm not sure how I feel about this one. I believe there are unit/mocks that ensure the buildpack is executing in the correct fashion and that the installer is called, as one would expect. 

What the installer does though, I think we'd have to be careful to not end up with very fragile tests. I also think that if there are any integration tests, they should probably be end-to-end tests in the rust-cnb metabuildpack or even in its own repo.

I think my preference would be to keep each buildpack as light as possible and aggregate the slower integration tests elsewhere.

**Comment by ForestEckhardt** [comment]
I think that we can use something the like `build-plan` buildpack to force detection to pass and then just run commands to see that `rust` available. I don't think that we need t do any more than that though.
